---
ssh: ascross

package: sonarr
name: Sonarr
version: 2.0.0.4855
architecture:
firmware: 2.6.0

config:
  general:
    developer: "Sonarr"
    website: "https://sonarr.tv"
    maintainer: "mafredri"
    email: "mafredri+adm@gmail.com"
    depends:
      - mono
    conflicts:
      - NzbDrone
    package: "PACKAGE"
    name: "NAME"
    version: "VERSION"
    architecture: "ARCHITECTURE"
    firmware: "FIRMWARE"
  adm-desktop:
    app:
      port: 8989
      protocol: http
      type: custom
      url: /
    privilege:
      accessible: users
      customizable: true
  register:
    boot-priority:
      start-order: 60
      stop-order: 60
    port:
      - 8989

case_sensitive: false
runpath: /usr/local/AppCentral/sonarr/lib
root: /usr
files:
  - /usr/bin/sqlite3
  - /usr/lib/libtinyxml2.so*
  - /usr/lib/libzen.so*
  - /usr/lib/libmediainfo.so*
  - /usr/lib/libsqlite3.so*
